envs:
  production:
    description: "My env description"
    devices: !!inc/file devices-production.yml
    app: firmware/app1
  develop:
    description: "Running directly from the stens"
    devices: !!inc/file devices-lab.yml
    app: firmware/app2
