build_binary:
    builder: particle photon
    source: firmware/

#testing:
#    script: testing/sample-test-script.py
#    device_update:
#        env_vars:
#            - $SPN_PARTICLE_TOKEN
#        devices:
#            - $DEVID_1
#        ota_method: particle
#        binary: auto
