# build_binary:
#     builder: 'particle photon'
#     binary_name: 'firmware/target/firmware.bin'
#     script: cd $SPN_BUILDER_SDK && make PLATFORM=photon APPDIR=$SPN_PROJECT_DIR/firmware && echo "nikolas"

testing:
   script: testing/sample-test-script.py
#        ota_method: particle
#        binary: auto
